In [3]:
import pandas as pd
import re
import numpy as np

# Load dataset
df = pd.read_csv("cleaned_jobs.csv")

# Show basic info
print(df.info())

# --- Clean Missing Values ---
df.dropna(subset=['Title', 'Company', 'Skills', 'Link'], inplace=True)
df['Experience'].fillna('0 years', inplace=True)
df['Salary'].fillna('Not Disclosed', inplace=True)
df['Location'].fillna('Remote', inplace=True)

# --- Normalize Text Columns ---
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^\w\s]', '', text)  # remove punctuation
    return text.strip()

df['Title'] = df['Title'].apply(clean_text)
df['Company'] = df['Company'].apply(clean_text)
df['Skills'] = df['Skills'].apply(clean_text)
df['Location'] = df['Location'].apply(clean_text)

# --- Parse Skills into List ---
df['Skills_List'] = df['Skills'].apply(lambda x: [i.strip() for i in x.split(',')])

# --- Convert Experience to Numeric ---
def extract_experience(exp):
    numbers = re.findall(r'\d+', str(exp))
    if len(numbers) == 0:
        return 0
    return int(numbers[0])

df['Experience_Years'] = df['Experience'].apply(extract_experience)

# --- Preview the cleaned dataframe ---
print(df.head())

df.to_csv("processed_data.csv", index=False)
print("Processed dataset saved as 'processed_data.csv'")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7650 entries, 0 to 7649
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       7650 non-null   object
 1   Company     7650 non-null   object
 2   Experience  7534 non-null   object
 3   Salary      1204 non-null   object
 4   Location    7617 non-null   object
 5   Skills      7567 non-null   object
 6   Link        7650 non-null   object
dtypes: object(7)
memory usage: 418.5+ KB
None
                                               Title               Company  \
0  internship trainee  retail branch banking  2 m...             hdfc bank
1  internship trainee  retail branch banking 2 mo...             hdfc bank
2                                   engineer trainee           upl limited
3                                   trainee engineer               siemens
4  astinil technologies is offering a intership a...  astinil technologies

  Experience         Salary                               Location  \
0    0-1 yrs  Not Disclosed               silchar durgapur bhadrak
1    0-1 yrs  Not Disclosed            guwahati kolkata jamshedpur
2    0-2 yrs  Not Disclosed                               jhagadia
3    0-1 yrs  Not Disclosed                                    goa
4    0-5 yrs    4-9 lacs pa  hybrid  hyderabad north goa bengaluru

                                              Skills  \
0  sales customer service marketing retail branch...
1  retail branch banking customer service sales b...
2  quality control production daily production en...
3  wave ema smt standard operating procedures pro...
4  java development spring boot java fullstack re...

                                                Link  \
0  https://www.naukri.com/job-listings-internship...
1  https://www.naukri.com/job-listings-internship...
2  https://www.naukri.com/job-listings-engineer-t...
3  https://www.naukri.com/job-listings-trainee-en...
4  https://www.naukri.com/job-listings-astinil-te...

                                         Skills_List  Experience_Years
0  [sales customer service marketing retail branc...                 0
1  [retail branch banking customer service sales ...                 0
2  [quality control production daily production e...                 0
3  [wave ema smt standard operating procedures pr...                 0
4  [java development spring boot java fullstack r...                 0
Processed dataset saved as 'processed_data.csv'

C:\Users\Ekaansh\AppData\Local\Temp\ipykernel_21684\825020895.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Experience'].fillna('0 years', inplace=True)
C:\Users\Ekaansh\AppData\Local\Temp\ipykernel_21684\825020895.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna('Not Disclosed', inplace=True)
C:\Users\Ekaansh\AppData\Local\Temp\ipykernel_21684\825020895.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Location'].fillna('Remote', inplace=True)